In [12]:
import numpy as np
z = np.arange(1,501)
print(z)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 24

In [14]:
z=z.reshape(5,4,25)
print(z)

[[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
    18  19  20  21  22  23  24  25]
  [ 26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42
    43  44  45  46  47  48  49  50]
  [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
    68  69  70  71  72  73  74  75]
  [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
    93  94  95  96  97  98  99 100]]

 [[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
   118 119 120 121 122 123 124 125]
  [126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142
   143 144 145 146 147 148 149 150]
  [151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167
   168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192
   193 194 195 196 197 198 199 200]]

 [[201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
   218 219 220 221 222 223 224 225]
  [226 227 228 229 230 231 232 23

In [15]:
print(z[3,2,-1])

375


In [38]:
# concatenate
x = [1,2,3,4,5,6,7,8,9]
y=[10,11,12,13,14,15,16,17,18]

a1 =np.array(x).reshape(3,3)
a2 =np.array(y).reshape(3,3)
print(a1)
print("----------------------------------")
print(a2)
print("----------------------------------")
z = np.concatenate((a1,a2),axis=0)
print(z)
print("----------------------------------")
z = np.concatenate((a1,a2),axis=1)
print(z)
print("----------------------------------")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------
[[10 11 12]
 [13 14 15]
 [16 17 18]]
----------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
----------------------------------
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
----------------------------------


In [42]:
#Array Split
x = np.arange(1,11)
z = np.array(x)
print(np.array_split(z,3))
print(np.array_split(z,6))

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9]), array([10])]


In [6]:
#where filter
x = np.arange(1,11)
z = np.array(x)
print(z)
print(np.where(z==7)) #index position
print(np.where(z%2==0)) #index position
print(np.where(z%2==0,"even","odd"))

[ 1  2  3  4  5  6  7  8  9 10]
(array([6], dtype=int64),)
(array([1, 3, 5, 7, 9], dtype=int64),)
['odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even' 'odd' 'even']


In [25]:
#Sorting
x = [[54,7,4,9],[12,46,32,75],[89,34,45,43]]
z = np.array(x)
print(z)
print("----------------------------------")
print(np.sort(z)) #row wise
print("----------------------------------")
print(np.sort(z,axis=0)) #column wise
print("----------------------------------")
print(np.sort(z,axis=1)) #row wise

[[54  7  4  9]
 [12 46 32 75]
 [89 34 45 43]]
----------------------------------
[[ 4  7  9 54]
 [12 32 46 75]
 [34 43 45 89]]
----------------------------------
[[12  7  4  9]
 [54 34 32 43]
 [89 46 45 75]]
----------------------------------
[[ 4  7  9 54]
 [12 32 46 75]
 [34 43 45 89]]


In [27]:
# numpy iteration
print(z)
for i in np.nditer(z):
    print(i)

[[54  7  4  9]
 [12 46 32 75]
 [89 34 45 43]]
54
7
4
9
12
46
32
75
89
34
45
43
