In [4]:
from abc import ABC,abstractmethod

class Defence(ABC):
    @abstractmethod
    def gun(self):
        pass
    def show(self):
        print("hello")
        
class Army(Defence):
    def gun(self):
        print("AK47")
        
class Navy(Army):
    def gun(self):
        print("AUG")
        
a = Army()
a.gun()
n = Navy()
n.gun()

AK47
AUG


In [9]:
from abc import ABC,abstractmethod
class employee:
    def getDetails(self):
        self.x = int(input("Enter Employee ID: "))
        self.name = input("Enter Name: ")
        self.sal = int(input("Enter Basic salary: "))
        
    def displayDetails(self):
        print(f"Employee ID: {self.x}")
        print(f"Employee Name: {self.name}")
        print(f"Employee Sal: {self.sal}")
        
    def salary(self):
        return self.sal
    
    @abstractmethod
    def emp_id(self):
        pass
    
class perks(employee):
    def emp_id(self):
        return self.x
    def calculate(self):
        self.DA = (self.sal*0.35)
        print(f"DA = {self.DA}")
        self.HRA = (self.sal*0.17)
        print(f"HRA = {self.HRA}")
        self.PF = (self.sal*0.12)
        print(f"PF = {self.PF}")
        
class NetSalary(perks):
    def emp_id(self):
        return self.x
    def total(self):
        print(f"Final Salary: {self.sal+self.DA+self.HRA+self.PF}")
    
obj=NetSalary()
obj.getDetails()
obj.displayDetails()
obj.calculate()
obj.total()
    

Enter Employee ID: 1
Enter Name: Dev
Enter Basic salary: 100000
Employee ID: 1
Employee Name: Dev
Employee Sal: 100000
DA = 35000.0
HRA = 17000.0
PF = 12000.0
Final Salary: 164000.0


In [12]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [13]:
y= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [17]:
z= np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
